title: とらち
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.625
  lightness: 0.625
  brandStrength: 1
  brandColors:
    - '#6E301E'
    - '#D1C4BB'
    - '#A39A88'
    - '#0C0B0D'
    - '#9A5C5C'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Torachitech
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.59597
layout_spectrum: 0.35919
